server.port=${PORT:8080}
app.base-url=https://website-4gr1.onrender.com
logging.level.org.atmosphere=warn
logging.level.web=error

vaadin.launch-browser=false

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example
spring.devtools.add-properties=false